### ISSUE TITLE
Crash [ en injectant des gsc ]

### ISSUE THREAD

**Issue by MrCoolskill** [NexoDevelopment/WiiU_BO2_Injector_FULLVER#2]
J'ai essayé d'injecter des menus tels que Jiggy, bossam ect...( venant du fichier des menus wiiu )  , ou d'autres gsc hors fichier venant de ps3/xbox que j'ai pu trouver sur certaines vidéos ytb , il y a bien les fichiers maps, mp , gametypes ect... et pourtant ma wiiu crash apres le chargement d'une partie en ecrivant " too [...] parameters... " . Si tu aurais une idée pour y remédier...    Merci d'avance ;)

**Comment by NexoDevelopment** [comment]
BO2 WiiU est en version 1.07 et les versions console en 1.19. Il faut trouver le source code de ces mod menu et enlever les aimbots, recompiler et ça devrait marcher !

Je ne peux rien y faire, ça vient du jeu et pas de l’injector.

Je te conseille l’Alca v2 et v3 et aussi le Batman v5

**Comment by gavinboz1** [comment]
Please talk English

**Comment by MrCoolskill** [comment]
Merci pr ton aide ;) d'ailleurs l'injector peut il injecter des gsc en zombie ? Car j'ai essayé d'injecter un fichier contenant ( maps , mp ect... ) mais avec gametypes_zm et dans l'invite de commande , ça n'a pas indiqué l'injection du gsc.

**Comment by NexoDevelopment** [comment]
STOP ASKING FOR MODS HOLY SHIT ITS LITERALLY FREE AND OPEN SOURCE
